# Generated by Django 5.2 on 2025-08-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vendor_approved",
            field=models.BooleanField(default=False),
        ),
    ]
